name: docker build

on:
   workflow_dispatch
   
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Docker
        uses: docker/login-action@v3  
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: maxoba/flask-python
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags}} 
            labels: ${{ steps.meta.outputs.labels }}           
                      
